#!/usr/bin/env python
# -*- coding: utf-8 -*-

import Tuio
from Recognizer import Recognizer, newHypothesis
from Events import Event
from Agent import Agent
import math
import Reactor

class RecognizerTap(Recognizer):
    #for debugging porpuses we have a count of instances
    allr = 0
    #Events generated by this recognizer
    E_NewTap = Event()
    def __init__(self):
        self.finger = None
        RecognizerTap.allr += 1
        print "new RecognizerTap, we are",RecognizerTap.allr
        Recognizer.__init__(self)
        self.cursorEvents = Tuio.TuioCursorEvents
        self.register_event(self.cursorEvents.newCursor,RecognizerTap.EventNewCursor)
        self.agent = Agent()
        self.events = (self.E_NewTap,)
        self.maxd = 10
        self.time = 0.5
        self.origin = None
    
    @newHypothesis
    def EventNewCursor(self,Cursor):
        self.finger = Cursor
        self.unregister_event(self.cursorEvents.newCursor)
        self.register_event(self.cursorEvents.moveCursor,RecognizerTap.EventMoveCursor)
        self.register_event(self.cursorEvents.removeCursor,RecognizerTap.EventRemoveCursor)
        Reactor.schedule_after(self.time,self,RecognizerTap.fail)
        self.origin = Cursor.pos
        self.acquire(Cursor)

    
    def EventMoveCursor(self,Cursor):
        if self.finger == Cursor:
            if self.dist(Cursor.pos,self.origin) > self.maxd:
                self.fail()
    
    def EventRemoveCursor(self,Cursor):
        if self.finger == Cursor:
            Reactor.cancel_schedule(self)
            self.unregister_event(self.cursorEvents.moveCursor)
            self.unregister_event(self.cursorEvents.removeCursor)
            self.complete()
            
    def execute(self):
        self.agent.pos = self.origin
        self.E_NewTap.call(self.agent)
        print "Tap!"
        self.fail()
    
    def __del__(self):
        RecognizerTap.allr -= 1
    
    @staticmethod
    def dist(a,b):
        dx,dy = (a[0]-b[0],a[1]-b[1])
        return math.sqrt(dx**2 + dy**2)
    
    def duplicate(self):
        d = RecognizerTap()
        Recognizer.copy_to(self,d)
        d.finger = self.finger
        d.origin = self.origin
        if not self.is_pristine():
            d.agent = self.agent
        return d
